version: "2"

services:
  nats:
    image: "nats:2.1.6"
    expose:
      - "4222"
    ports:
      - "8222:8222"
    hostname: nats-server

  api:
    build:
      context: "./api"
    entrypoint: /go/api
    links:
      - nats
    environment:
      - "NATS_URI=nats://nats:4222"
    depends_on:
      - nats
    ports:
      - "8080:8080"

  services:
    build:
      context: "./services"
    entrypoint: /go/services
    links:
      - nats
    environment:
      - "NATS_URI=nats://nats:4222"
    depends_on:
      - nats
    ports:
      - "8181:8181"